language: node_js
node_js:
  - 14
addons:
  apt:
    packages:
      - xvfb
      - libsecret-1-0
cache:
  npm: false
  directories:
    - '~/.pnpm-store'
before_install:
  - | # reference: https://www.electronjs.org/docs/tutorial/testing-on-headless-ci
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
script:
  - node scripts/build.js
  - pnpm test
